/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazcrud;

import static interfazcrud.ClientesFichero.getFicheroClientes;
import static interfazcrud.CocheFichero.getFicheroCoche;
import static interfazcrud.ConcesionarioFichero.getFicheroConcesionario;
import static interfazcrud.PersonalFichero.getFicheroPersonal;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.DOMException;
import org.w3c.dom.DOMImplementation;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Text;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.XMLReader;
import org.xml.sax.helpers.XMLReaderFactory;
import javax.xml.stream.XMLStreamReader; 
import javax.xml.stream.XMLStreamConstants; 
import javax.xml.stream.XMLStreamException;
import javax.xml.xquery.XQConnection;
import javax.xml.xquery.XQDataSource;
import javax.xml.xquery.XQException;
/**
 *
 * @author anton
 */
public class Interfaz extends javax.swing.JFrame {
    ArrayList<Coche> coches = new ArrayList<Coche>();
    ArrayList<Concesionario> concesionarios = new ArrayList<Concesionario>();
    ArrayList<Clientes> clientes = new ArrayList<Clientes>();
    ArrayList<Personal> personales = new ArrayList<Personal>();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() throws SAXException,IOException, SQLException, ClassNotFoundException,
            InstantiationException, IllegalAccessException, XQException, XMLStreamException{
        
        initComponents();
        bloquear();
        bloquear_concesionario();
        bloquear_personal();
        bloquear_clientes();
       // coches = getFicheroCoche();
        personales = getFicheroPersonal();
        concesionarios =getFicheroConcesionario();
        clientes = getFicheroClientes();
        
         ExistDB db = new ExistDB();
         XQConnection paquete;
         paquete = db.obtenConexion();
         db.leerXS(paquete,coches);
         

        
  
        //procesador.parse(fileXML);
        //procesador_c.parse(fileXML);
        //procesador_cl.parse(fileXML);
        for(int i = 0;i < coches.size();i++){
             jComboBox1.addItem(coches.get(i).getNombre());     
        }
        for(int i = 0; i < concesionarios.size();i++)
            jComboBox2.addItem(concesionarios.get(i).getNombre());
        for(int i = 0; i < personales.size();i++)
            jComboBox3.addItem(personales.get(i).getNombre());
        
        
        ActualizoTablaCoche();
        ActualizarTablaPersonal();
        ActualizartablaConcesionario();
        ActualizaTablaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        text_modelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_matricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_introducir = new javax.swing.JButton();
        b_guardar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        b_actualizar = new javax.swing.JButton();
        b_eliminar = new javax.swing.JButton();
        b_insertar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        text_kilometros = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_introducir_c = new javax.swing.JButton();
        bt_eliminar_c = new javax.swing.JButton();
        bt_actualizar_c = new javax.swing.JButton();
        txt_nombre_c = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_tlf_c = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_id_C = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_direccion_c = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_id_p = new javax.swing.JTextField();
        txt_nombre_p = new javax.swing.JTextField();
        txt_apellido_p = new javax.swing.JTextField();
        txt_departamento_p = new javax.swing.JTextField();
        bt_introducir_p = new javax.swing.JButton();
        bt_eliminar_p = new javax.swing.JButton();
        bt_actualizar_p = new javax.swing.JButton();
        bt_cancelar_p = new javax.swing.JButton();
        bt_guardar_p = new javax.swing.JButton();
        bt_anadir_p = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        panel4 = new java.awt.Panel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        txt_dni_cl = new javax.swing.JTextField();
        txt_apellido_cl = new javax.swing.JTextField();
        Dni = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_nombre_cl = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_tlf_cl = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bt_cancelar_cli = new javax.swing.JButton();
        bt_guardar_cli = new javax.swing.JButton();
        bt_anadir_cli = new javax.swing.JButton();
        bt_introducir_cli = new javax.swing.JButton();
        bt_eliminar_cli = new javax.swing.JButton();
        bt_actualizar_cli = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Marca");

        text_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Modelo");

        jLabel3.setText("Matricula");

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Matricula", "Kilometros"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bt_introducir.setText("Añadir");
        bt_introducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_introducirActionPerformed(evt);
            }
        });

        b_guardar.setText("Guardar");
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        b_actualizar.setText("Actualizar coche");
        b_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_actualizarActionPerformed(evt);
            }
        });

        b_eliminar.setText("Eliminar");
        b_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eliminarActionPerformed(evt);
            }
        });

        b_insertar.setText(" Introducir nuevo coche");
        b_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_insertarActionPerformed(evt);
            }
        });

        jLabel16.setText("Kilometros");

        guardar.setText("Salir");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_insertar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(b_eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(text_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel16))
                        .addGap(56, 56, 56)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_kilometros)
                            .addComponent(text_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bt_introducir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(guardar))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(b_insertar)
                        .addGap(38, 38, 38)
                        .addComponent(b_eliminar)
                        .addGap(57, 57, 57)
                        .addComponent(b_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)))))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_cancelar)
                        .addComponent(b_guardar)
                        .addComponent(bt_introducir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(text_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(text_kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(guardar))
        );

        jTabbedPane3.addTab("Coches", panel1);

        jTable2 = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Direccion", "Telefono"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("Nombre");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Añadir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_introducir_c.setText("introducir nuevo concesioario");
        btn_introducir_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_introducir_cActionPerformed(evt);
            }
        });

        bt_eliminar_c.setText(" Eliminar Concesionario");
        bt_eliminar_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_cActionPerformed(evt);
            }
        });

        bt_actualizar_c.setText("Actualizar concesionario");
        bt_actualizar_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualizar_cActionPerformed(evt);
            }
        });

        txt_nombre_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_cActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefono");

        jLabel6.setText("Id");

        txt_id_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_CActionPerformed(evt);
            }
        });

        jLabel7.setText("Direccion");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel4))
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel6)))
                                .addGap(23, 23, 23)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_nombre_c, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_id_C, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_tlf_c, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_direccion_c, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(174, 174, 174)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_introducir_c, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_eliminar_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_actualizar_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_id_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txt_direccion_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(btn_introducir_c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(bt_eliminar_c)
                        .addGap(57, 57, 57)
                        .addComponent(bt_actualizar_c)
                        .addGap(70, 70, 70)))
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_nombre_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txt_tlf_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(26, 26, 26)
                        .addComponent(jButton4))))
        );

        jTabbedPane3.addTab("Concesionario", panel2);

        jTable3 = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Departamento", "Apellido"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel8.setText("Nombre");

        jLabel9.setText("Id");

        jLabel10.setText("Departamento");

        jLabel11.setText("Apellido");

        bt_introducir_p.setText("Introducir personal");
        bt_introducir_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_introducir_pActionPerformed(evt);
            }
        });

        bt_eliminar_p.setText("Eliminar personal");
        bt_eliminar_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_pActionPerformed(evt);
            }
        });

        bt_actualizar_p.setText("Actualizar personal");
        bt_actualizar_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualizar_pActionPerformed(evt);
            }
        });

        bt_cancelar_p.setText("Cancelar");
        bt_cancelar_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelar_pActionPerformed(evt);
            }
        });

        bt_guardar_p.setText("Guardar");
        bt_guardar_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardar_pActionPerformed(evt);
            }
        });

        bt_anadir_p.setText("Añadir");
        bt_anadir_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_anadir_pActionPerformed(evt);
            }
        });

        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_id_p, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre_p, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(47, 47, 47)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_apellido_p, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(txt_departamento_p))
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(bt_cancelar_p, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(bt_guardar_p, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(bt_anadir_p, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addContainerGap())))
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_introducir_p, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(bt_eliminar_p, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_actualizar_p, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_introducir_p)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(bt_eliminar_p)
                        .addGap(57, 57, 57)
                        .addComponent(bt_actualizar_p))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txt_id_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_apellido_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(txt_nombre_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_departamento_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cancelar_p)
                            .addComponent(bt_guardar_p)
                            .addComponent(bt_anadir_p))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(6, 6, 6))))
        );

        jTabbedPane3.addTab("Personal", panel3);

        jTable4 = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Dni", "Nombre", "Apellido", "Telefono"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        Dni.setText("Dni");

        jLabel13.setText("Apellido");

        jLabel14.setText("Nombre");

        jLabel15.setText("Telefono");

        bt_cancelar_cli.setText("Cancelar");
        bt_cancelar_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelar_cliActionPerformed(evt);
            }
        });

        bt_guardar_cli.setText("Guardar");
        bt_guardar_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardar_cliActionPerformed(evt);
            }
        });

        bt_anadir_cli.setText("Añadir");
        bt_anadir_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_anadir_cliActionPerformed(evt);
            }
        });

        bt_introducir_cli.setText("Introducir un cliente nuevo");
        bt_introducir_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_introducir_cliActionPerformed(evt);
            }
        });

        bt_eliminar_cli.setText("Eliminar Cliente");
        bt_eliminar_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_cliActionPerformed(evt);
            }
        });

        bt_actualizar_cli.setText("Actualizar cliente");
        bt_actualizar_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualizar_cliActionPerformed(evt);
            }
        });

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_actualizar_cli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_eliminar_cli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_introducir_cli, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(Dni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addComponent(txt_nombre_cl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addComponent(txt_dni_cl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_apellido_cl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(txt_tlf_cl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(bt_cancelar_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(bt_guardar_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(bt_anadir_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(597, 597, 597)
                                .addComponent(jButton6))))))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addComponent(bt_introducir_cli)
                        .addGap(3, 3, 3)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_eliminar_cli)
                        .addGap(61, 61, 61)
                        .addComponent(bt_actualizar_cli)
                        .addGap(90, 90, 90))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre_cl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tlf_cl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(19, 19, 19))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                                .addComponent(Dni)
                                .addGap(13, 13, 13))
                            .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_dni_cl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_apellido_cl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bt_guardar_cli)
                                    .addComponent(bt_cancelar_cli)
                                    .addComponent(bt_anadir_cli))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(30, 30, 30))))
                    .addComponent(jButton6)))
        );

        jTabbedPane3.addTab("Clientes", panel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_insertarActionPerformed
        limpiar_texto();
        text_nombre.setEnabled(true);
        text_modelo.setEnabled(true);
        text_matricula.setEnabled(true);
        text_kilometros.setEnabled(true);
        b_eliminar.setEnabled(false);
        b_actualizar.setEnabled(false);
        b_guardar.setEnabled(false);
    }//GEN-LAST:event_b_insertarActionPerformed
 public void anadirConcesionario() throws SQLException{

    }
    private void b_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eliminarActionPerformed
   
        try{ 
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            int res = jTable1.getSelectedRow();
            ExistDB db = new ExistDB();
             XQConnection paquete = null;
             paquete = db.obtenConexion();
            db.eliminarCoche(paquete,coches.get(res));
            
            coches.remove(res);
            modelo = (DefaultTableModel) jTable1.getModel();

            modelo.removeRow(res); // borra de la fila y el row para la fila selecionada con el raton

        }catch (Exception e){
            // JOptionPane.showMessageDialog(null, "selecion una fila "); //muestra una ventana emergente de error
        }
        
        ActualizoTablaCoche();
        limpiar_texto();
    }//GEN-LAST:event_b_eliminarActionPerformed
    public void ActualizarTablaPersonal(){
        int i = 0;
        for(Personal cn : personales){
            jTable3.setValueAt(cn.getDepartamento(), i, 2);
            jTable3.setValueAt(cn.getNombre(), i, 1);
            jTable3.setValueAt(Integer.toString(cn.getId()), i, 0);
            jTable3.setValueAt(cn.getApellido(), i, 3);
            i++;
        }
    
    }
    private void b_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_actualizarActionPerformed
        text_nombre.setEnabled(true);
        text_modelo.setEnabled(true);
        text_matricula.setEnabled(true);
        text_kilometros.setEnabled(true);
        b_insertar.setEnabled(false);
        b_eliminar.setEnabled(false);
        bt_introducir.setEnabled(false);
    }//GEN-LAST:event_b_actualizarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        limpiar_texto();
        b_insertar.setEnabled(true);
        b_actualizar.setEnabled(true);
        b_eliminar.setEnabled(true);
        bloquear();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        int res = jTable1.getSelectedRow(); //para que te diga el numero de la posicion del array que has selecionado
        coches.get(res).setNombre(text_nombre.getText());
        coches.get(res).setModelo(text_modelo.getText());
        coches.get(res).setMatricula(Integer.parseInt(text_matricula.getText()));
        coches.get(res).setkilometros(Integer.parseInt(text_kilometros.getText()));
        ActualizoTablaCoche();
        bloquear();
         b_insertar.setEnabled(true);
        b_eliminar.setEnabled(true);
        bt_introducir.setEnabled(true);
        b_guardar.setEnabled(true);
        bt_introducir.setEnabled(true);
       
    }//GEN-LAST:event_b_guardarActionPerformed
    public void ActualizoTablaCoche(){
    int i = 0;
        for(Coche c : coches){
            jTable1.setValueAt(c.getNombre(), i, 0);
            jTable1.setValueAt(c.getModelo(), i, 1);
            jTable1.setValueAt(Integer.toString(c.getMatricula()), i, 2);
            jTable1.setValueAt(Integer.toString(c.getkilometros()), i, 3);
            i++;
        }
    
    
    
    }
    private void bt_introducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_introducirActionPerformed
        Coche coche = new Coche();
        coche.setNombre(text_nombre.getText());
        coche.setModelo(text_modelo.getText());
        coche.setMatricula(Integer.parseInt(text_matricula.getText()));
        coche.setkilometros(Integer.parseInt(text_kilometros.getText()));
        coches.add(coche);
        
        ExistDB db = new ExistDB();
         XQConnection paquete = null;
        try {
            paquete = db.obtenConexion();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (XQException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            db.insertarXS(paquete,coche);
        } catch (XQException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        ActualizoTablaCoche();
        bloquear();
        limpiar_texto();
         b_insertar.setEnabled(true);
        b_actualizar.setEnabled(true); 
        b_guardar.setEnabled(true);
    }//GEN-LAST:event_bt_introducirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int res = jTable1.getSelectedRow(); //para que te diga el numero de la posicion del array que has selecionado
        text_nombre.setText(coches.get(res).getNombre());//para que te devuelva el nombre y lo muestre en el text
        text_modelo.setText(coches.get(res).getModelo());
        //valueof convierte el int (Matricula) a string
        text_matricula.setText(String.valueOf(coches.get(res).getMatricula()));
        text_kilometros.setText(String.valueOf(coches.get(res).getkilometros()));
    }//GEN-LAST:event_jTable1MouseClicked

    private void text_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nombreActionPerformed

    private void txt_id_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_CActionPerformed

    private void txt_nombre_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_cActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar_texto_concesionario();
        btn_introducir_c.setEnabled(true);
        bt_eliminar_c.setEnabled(true);
        bt_actualizar_c.setEnabled(true);
        bloquear_concesionario();
          btn_introducir_c.setEnabled(true);
        bt_eliminar_c.setEnabled(true);
        jButton3.setEnabled(true);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_introducir_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_introducir_cActionPerformed
        limpiar_texto_concesionario();
        txt_id_C.setEnabled(true);
        txt_nombre_c.setEnabled(true);
        txt_direccion_c.setEnabled(true);
        txt_tlf_c.setEnabled(true);
        bt_eliminar_c.setEnabled(false);
       bt_actualizar_c.setEnabled(false);
       jButton2.setEnabled(false);
        try {
            anadirConcesionario();
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_introducir_cActionPerformed

    private void bt_eliminar_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_cActionPerformed
          try{
            DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
            int res = jTable2.getSelectedRow();
            concesionarios.remove(res);
            modelo = (DefaultTableModel) jTable2.getModel();

            modelo.removeRow(res); // borra de la fila y el row para la fila selecionada con el raton

        }catch (Exception e){
            // JOptionPane.showMessageDialog(null, "selecion una fila "); //muestra una ventana emergente de error
        }
        int i = 0;
        ActualizartablaConcesionario();
        limpiar_texto_concesionario();
        bloquear_concesionario();
    }//GEN-LAST:event_bt_eliminar_cActionPerformed
    public void ActualizartablaConcesionario(){
    int i = 0;
        for(Concesionario cn : concesionarios){
            jTable2.setValueAt(cn.getDireccion(), i, 2);
            jTable2.setValueAt(cn.getNombre(), i, 1);
            jTable2.setValueAt(Integer.toString(cn.getId()), i, 0);
            jTable2.setValueAt(Integer.toString(cn.getTelefono()), i, 3);
            i++;
        }
    }
    private void bt_actualizar_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizar_cActionPerformed
        txt_id_C.setEnabled(true);
         txt_nombre_c.setEnabled(true);
         txt_direccion_c.setEnabled(true);
         txt_tlf_c.setEnabled(true);
         bt_eliminar_c.setEnabled(false);
        btn_introducir_c.setEnabled(false);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_bt_actualizar_cActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int res = jTable2.getSelectedRow(); //para que te diga el numero de la posicion del array que has selecionado
        concesionarios.get(res).setNombre(txt_nombre_c.getText());
        concesionarios.get(res).setDireccion(txt_direccion_c.getText());
        concesionarios.get(res).setId(Integer.parseInt(txt_id_C.getText()));
        concesionarios.get(res).setTelefono(Integer.parseInt(txt_tlf_c.getText()));
        
        ActualizartablaConcesionario();
        bloquear_concesionario();
        bt_eliminar_c.setEnabled(true);
        btn_introducir_c.setEnabled(true);
         bt_introducir.setEnabled(true);
         jButton3.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Concesionario conc = new Concesionario();
        conc.setNombre(txt_nombre_c.getText());
        conc.setDireccion(txt_direccion_c.getText());
        conc.setId(Integer.parseInt(txt_id_C.getText()));
        conc.setTelefono(Integer.parseInt(txt_tlf_c.getText()));
        concesionarios.add(conc);
        
         
       ActualizartablaConcesionario();
       
        bloquear_concesionario();
        limpiar_texto_concesionario();
        bt_eliminar_c.setEnabled(true);
        bt_actualizar_c.setEnabled(true);  
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bt_introducir_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_introducir_pActionPerformed
        limpiar_texto_personal();
        txt_id_p.setEnabled(true);
        txt_nombre_p.setEnabled(true);
        txt_apellido_p.setEnabled(true);
        txt_departamento_p.setEnabled(true);
        bt_eliminar_p.setEnabled(false);
        bt_actualizar_p.setEnabled(false);
       bt_guardar_p.setEnabled(false);
    }//GEN-LAST:event_bt_introducir_pActionPerformed

   static void  CrearElemento(String datoEmple, String valor,Element raiz, Document document){

        Element elem = document.createElement(datoEmple); 
        Text text = document.createTextNode(valor); //damos valor
        raiz.appendChild(elem); //pegamos el elemento hijo a la raiz
        elem.appendChild(text); //pegamos el valor
    }
    
    public void NuevoFicheroCocheXML(){
         
    DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();

    try{
        
      DocumentBuilder builder = factory.newDocumentBuilder();
      DOMImplementation implementation = builder.getDOMImplementation();
      Document document = implementation.createDocument(null, "coches", null);
      document.setXmlVersion("1.0"); 
      
        for(int i = 0;i < coches.size();i++) {
          Element raiz = document.createElement("coches");  
          document.getDocumentElement().appendChild(raiz);
          CrearElemento("nombre", String.valueOf(coches.get(i).getNombre()), raiz, document); 
          CrearElemento("modelo", String.valueOf(coches.get(i).getModelo()), raiz, document); 
          CrearElemento("Matricula", Integer.toString(coches.get(i).getMatricula()), raiz, document); 
          CrearElemento("Kilometros", Integer.toString(coches.get(i).getkilometros()), raiz, document); 
      } 

      Source source = new DOMSource(document);
      Result result =  new StreamResult(new java.io.File("coche.xml"));        
      Transformer transformer = TransformerFactory.newInstance().newTransformer();
      transformer.transform(source, result);

     }catch(ParserConfigurationException | TransformerException | DOMException e){ } 
    
    }
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
       
       // CocheFichero.NuevoFicheroCoche(coches);
       // PersonalFichero.NuevoFicheroPersonal(personales);
       // ConcesionarioFichero.NuevoFicheroConcesionario(concesionarios);
       // ClientesFichero.NuevoFicheroPersonal(clientes);
        
        EscrituraXmlCoche escribir = new  EscrituraXmlCoche();
        //System.out.println("linea 1165 interfaz ");
        NuevoFicheroCocheXML();
           EscrituraXML_personal a = null;
         EscrituraXmlCliente c = null;
         EscrituraXmlCoche car = null;
         System.out.println("guardando lectura xml coche");

        try {
            car.escritura(coches);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            c.escritura(clientes);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            a.escritura(personales);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_guardarActionPerformed

    private void bt_eliminar_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_pActionPerformed
             try{
            DefaultTableModel modelo = (DefaultTableModel) jTable3.getModel();
            int res = jTable3.getSelectedRow();
            personales.remove(res);
            modelo = (DefaultTableModel) jTable3.getModel();

            modelo.removeRow(res); // borra de la fila y el row para la fila selecionada con el raton

        }catch (Exception e){
            // JOptionPane.showMessageDialog(null, "selecion una fila "); //muestra una ventana emergente de error
        }

        int i = 0;
        for(Personal cn : personales){
            jTable3.setValueAt(cn.getDepartamento(), i, 2);
            jTable3.setValueAt(cn.getNombre(), i, 1);
            jTable3.setValueAt(Integer.toString(cn.getId()), i, 0);
            jTable3.setValueAt(cn.getApellido(), i, 3);
             
            i++;
        }
        limpiar_texto_personal();
        bloquear_personal();
    }//GEN-LAST:event_bt_eliminar_pActionPerformed

    private void bt_actualizar_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizar_pActionPerformed
        txt_id_p.setEnabled(true);
        txt_nombre_p.setEnabled(true);
        txt_apellido_p.setEnabled(true);
        txt_departamento_p.setEnabled(true);
         bt_eliminar_p.setEnabled(false);
        bt_introducir_p.setEnabled(false);
        bt_anadir_p.setEnabled(false);
    }//GEN-LAST:event_bt_actualizar_pActionPerformed

    private void bt_cancelar_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelar_pActionPerformed
        limpiar_texto_personal();
        bt_introducir_p.setEnabled(true);
        bt_eliminar_p.setEnabled(true);
        bt_actualizar_p.setEnabled(true);
        bloquear_personal();
          bt_introducir_p.setEnabled(true);
        bt_eliminar_p.setEnabled(true);
        bt_guardar_p.setEnabled(true);
        bt_anadir_p.setEnabled(true);
    }//GEN-LAST:event_bt_cancelar_pActionPerformed

    private void bt_guardar_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardar_pActionPerformed
         int res = jTable3.getSelectedRow(); //para que te diga el numero de la posicion del array que has selecionado
        personales.get(res).setNombre(txt_nombre_p.getText());
        personales.get(res).setApellido(txt_apellido_p.getText());
        personales.get(res).setId(Integer.parseInt(txt_id_p.getText()));
        personales.get(res).setDepartamento(txt_departamento_p.getText());
        ActualizarTablaPersonal();
        bloquear_personal();
         bt_eliminar_p.setEnabled(true);
         bt_introducir_p.setEnabled(true);
         bt_guardar_p.setEnabled(true);
         bt_actualizar_p.setEnabled(true);
         bt_eliminar_p.setEnabled(true);
        bt_introducir_p.setEnabled(true);
        bt_anadir_p.setEnabled(true);
    }//GEN-LAST:event_bt_guardar_pActionPerformed

    private void bt_anadir_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_anadir_pActionPerformed
        Personal per = new Personal();
        
        per.setNombre(txt_nombre_p.getText());
        per.setApellido(txt_apellido_p.getText());
        per.setId(Integer.parseInt(txt_id_p.getText()));
        per.setDepartamento(txt_departamento_p.getText());
        personales.add(per);

        int i = 0;
        for(Personal p : personales){
           jTable3.setValueAt(p.getDepartamento(), i, 2);
            jTable3.setValueAt(p.getNombre(), i, 1);
            jTable3.setValueAt(Integer.toString(p.getId()), i, 0);
            jTable3.setValueAt(p.getApellido(), i, 3);
            i++;
            jComboBox2.addItem(p.getNombre());
        }
        bloquear_personal();
        limpiar_texto_personal();
        bt_eliminar_p.setEnabled(true);
        bt_actualizar_p.setEnabled(true);
        bt_guardar_p.setEnabled(true);
    }//GEN-LAST:event_bt_anadir_pActionPerformed

    private void bt_introducir_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_introducir_cliActionPerformed
       limpiar_texto_clientes();
       txt_dni_cl.setEnabled(true);
       txt_nombre_cl.setEnabled(true);
       txt_apellido_cl.setEnabled(true);
       txt_tlf_cl.setEnabled(true);
       bt_eliminar_cli.setEnabled(false);
        bt_actualizar_cli.setEnabled(false);
       bt_guardar_cli.setEnabled(false);
    }//GEN-LAST:event_bt_introducir_cliActionPerformed

    private void bt_eliminar_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_cliActionPerformed
           try{
            DefaultTableModel modelo = (DefaultTableModel) jTable4.getModel();
            int res = jTable4.getSelectedRow();
            clientes.remove(res);
            modelo = (DefaultTableModel) jTable4.getModel();

            modelo.removeRow(res); // borra de la fila y el row para la fila selecionada con el raton

        }catch (Exception e){
            // JOptionPane.showMessageDialog(null, "selecion una fila "); //muestra una ventana emergente de error
        }
       
        limpiar_texto_clientes();
        bloquear_clientes();
    }//GEN-LAST:event_bt_eliminar_cliActionPerformed
    public void ActualizaTablaClientes() throws SQLException{
     int i = 0;
        for(Clientes cn : clientes){
            jTable4.setValueAt(cn.getDni(), i, 0);
            jTable4.setValueAt(cn.getNombre(), i, 1);
            jTable4.setValueAt(cn.getApellido(), i, 2);
            jTable4.setValueAt(Integer.toString(cn.getTelefono()), i, 3);
            i++;
        }
    }
    private void bt_actualizar_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizar_cliActionPerformed
       txt_dni_cl.setEnabled(true);
       txt_nombre_cl.setEnabled(true);
       txt_apellido_cl.setEnabled(true);
       txt_tlf_cl.setEnabled(true);
        bt_eliminar_cli.setEnabled(false);
        bt_introducir_cli.setEnabled(false);
        bt_anadir_cli.setEnabled(false);
    }//GEN-LAST:event_bt_actualizar_cliActionPerformed

    private void bt_cancelar_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelar_cliActionPerformed
        limpiar_texto_clientes();
        bt_introducir_cli.setEnabled(true);
        bt_eliminar_cli.setEnabled(true);
        bt_actualizar_cli.setEnabled(true);
        bloquear_personal();
          bt_introducir_cli.setEnabled(true);
        bt_eliminar_cli.setEnabled(true);
        bt_guardar_cli.setEnabled(true);
        bt_anadir_cli.setEnabled(true);
    }//GEN-LAST:event_bt_cancelar_cliActionPerformed

    private void bt_guardar_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardar_cliActionPerformed
          int res = jTable4.getSelectedRow(); //para que te diga el numero de la posicion del array que has selecionado
        clientes.get(res).setDni(txt_dni_cl.getText());
        clientes.get(res).setApellido(txt_apellido_cl.getText());
        clientes.get(res).setTelefono(Integer.parseInt(txt_tlf_cl.getText()));
        clientes.get(res).setNombre(txt_nombre_cl.getText());
        int i = 0;
        for(Clientes cn : clientes){
            jTable4.setValueAt(cn.getDni(), i, 0);
            jTable4.setValueAt(cn.getNombre(), i, 1);
            jTable4.setValueAt(cn.getApellido(), i, 2);
            jTable4.setValueAt(Integer.toString(cn.getTelefono()), i, 3);
            i++;
            jComboBox3.addItem(cn.getNombre());
        }
        limpiar_texto_clientes();
        bloquear_clientes();
        bt_eliminar_cli.setEnabled(true);
        bt_introducir_cli.setEnabled(true);
        bt_anadir_cli.setEnabled(true);
    }//GEN-LAST:event_bt_guardar_cliActionPerformed

    private void bt_anadir_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_anadir_cliActionPerformed
        Clientes cli = new Clientes();
        cli.setNombre(txt_nombre_cl.getText());
        cli.setApellido(txt_apellido_cl.getText());
        cli.setTelefono(Integer.parseInt(txt_tlf_cl.getText()));
        cli.setDni(txt_dni_cl.getText());
        clientes.add(cli);
        int e;
       
        try {
            ActualizaTablaClientes();
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
         bloquear_clientes();
         limpiar_texto_clientes();
         bt_eliminar_cli.setEnabled(true);
        bt_actualizar_cli.setEnabled(true);
       bt_guardar_cli.setEnabled(true);
         
    }//GEN-LAST:event_bt_anadir_cliActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
         int res = jTable2.getSelectedRow(); //para que te diga el numero de la posicion del array que has selecionado
        txt_nombre_c.setText(concesionarios.get(res).getNombre());//para que te devuelva el nombre y lo muestre en el text
        txt_direccion_c.setText(concesionarios.get(res).getDireccion());
        //valueof convierte el int (Matricula) a string
        txt_id_C.setText(String.valueOf(concesionarios.get(res).getId()));
        txt_tlf_c.setText(String.valueOf(concesionarios.get(res). getTelefono()));
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
       int res = jTable3.getSelectedRow(); //para que te diga el numero de la posicion del array que has selecionado
        txt_nombre_p.setText(personales.get(res).getNombre());//para que te devuelva el nombre y lo muestre en el text
        txt_departamento_p.setText(personales.get(res).getDepartamento());
        txt_apellido_p.setText(personales.get(res).getApellido());
        txt_id_p.setText(String.valueOf(personales.get(res). getId()));
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
         int res = jTable4.getSelectedRow(); //para que te diga el numero de la posicion del array que has selecionado
        txt_nombre_cl.setText(clientes.get(res).getNombre());//para que te devuelva el nombre y lo muestre en el text
        txt_dni_cl.setText(clientes.get(res).getDni());
        txt_apellido_cl.setText(clientes.get(res).getApellido());
        txt_tlf_cl.setText(String.valueOf(clientes.get(res). getTelefono()));
    }//GEN-LAST:event_jTable4MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       // CocheFichero.NuevoFicheroCoche(coches);
       // PersonalFichero.NuevoFicheroPersonal(personales);
        // ConcesionarioFichero.NuevoFicheroConcesionario(concesionarios);
        // ClientesFichero.NuevoFicheroPersonal(clientes);
            EscrituraXML_personal a = null;
         EscrituraXmlCliente c = null;
         EscrituraXmlCoche car = null;
             System.out.println("guardando lectura xml coche");
  
        try {
            car.escritura(coches);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            c.escritura(clientes);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            a.escritura(personales);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       //CocheFichero.NuevoFicheroCoche(coches);
        //PersonalFichero.NuevoFicheroPersonal(personales);
        // ConcesionarioFichero.NuevoFicheroConcesionario(concesionarios);
        // ClientesFichero.NuevoFicheroPersonal(clientes);
         EscrituraXML_personal a = null;
         EscrituraXmlCliente c = null;
         EscrituraXmlCoche car = null;
             System.out.println("guardando lectura xml coche");
 
        try {
            car.escritura(coches);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            c.escritura(clientes);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            a.escritura(personales);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //CocheFichero.NuevoFicheroCoche(coches);
        //PersonalFichero.NuevoFicheroPersonal(personales);
        // ConcesionarioFichero.NuevoFicheroConcesionario(concesionarios);
        // ClientesFichero.NuevoFicheroPersonal(clientes);
            EscrituraXML_personal a = null;
         EscrituraXmlCliente c = null;
         EscrituraXmlCoche car = null;
             System.out.println("guardando lectura xml coche");
        try {
            car.escritura(coches);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            c.escritura(clientes);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            a.escritura(personales);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseClicked
   public int buscar(int id){
       int posicion = 0;
       boolean entrar = false;
        for(int i = 0;i <= coches.size() && entrar !=true ;i++){
            if(coches.get(i).getMatricula()== id){
              entrar = true;
              posicion = i;
            }
               
        }
        return posicion;
    }    
   public void limpiar_texto(){
        text_nombre.setText("");
         text_modelo.setText("");
         text_matricula.setText("");
         text_kilometros.setText("");
    }
   public void limpiar_texto_personal(){
       txt_id_p.setText("");
       txt_nombre_p.setText("");
       txt_apellido_p.setText("");
   }
    public void limpiar_texto_clientes(){
       txt_dni_cl.setText("");
       txt_nombre_cl.setText("");
       txt_apellido_cl.setText("");
       txt_tlf_cl.setText("");
   }
   public void limpiar_texto_concesionario(){
        txt_id_C.setText("");
         txt_nombre_c.setText("");
         txt_direccion_c.setText("");
         txt_tlf_c.setText("");
    }
    public void bloquear_concesionario(){
        txt_id_C.setEnabled(false);
         txt_nombre_c.setEnabled(false);
         txt_direccion_c.setEnabled(false);
         txt_tlf_c.setEnabled(false);
    }
    public void bloquear_clientes(){
     txt_dni_cl.setEnabled(false);
       txt_nombre_cl.setEnabled(false);
       txt_apellido_cl.setEnabled(false);
       txt_tlf_cl.setEnabled(false);
    
    }
      public void bloquear_personal(){
        txt_id_p.setEnabled(false);
         txt_nombre_p.setEnabled(false);
         txt_apellido_p.setEnabled(false);
         txt_departamento_p.setEnabled(false);
    }
    public void bloquear(){
     text_nombre.setEnabled(false);
        text_modelo.setEnabled(false);
        text_matricula.setEnabled(false);
        text_kilometros.setEnabled(false);
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException, XMLStreamException, InstantiationException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        try {
            new Interfaz().setVisible(true);
        } catch (SAXException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (XQException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dni;
    private javax.swing.JButton b_actualizar;
    private javax.swing.JButton b_eliminar;
    private javax.swing.JButton b_guardar;
    private javax.swing.JButton b_insertar;
    private javax.swing.JButton bt_actualizar_c;
    private javax.swing.JButton bt_actualizar_cli;
    private javax.swing.JButton bt_actualizar_p;
    private javax.swing.JButton bt_anadir_cli;
    private javax.swing.JButton bt_anadir_p;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cancelar_cli;
    private javax.swing.JButton bt_cancelar_p;
    private javax.swing.JButton bt_eliminar_c;
    private javax.swing.JButton bt_eliminar_cli;
    private javax.swing.JButton bt_eliminar_p;
    private javax.swing.JButton bt_guardar_cli;
    private javax.swing.JButton bt_guardar_p;
    private javax.swing.JButton bt_introducir;
    private javax.swing.JButton bt_introducir_cli;
    private javax.swing.JButton bt_introducir_p;
    private javax.swing.JButton btn_introducir_c;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private javax.swing.JTextField text_kilometros;
    private javax.swing.JTextField text_matricula;
    private javax.swing.JTextField text_modelo;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField txt_apellido_cl;
    private javax.swing.JTextField txt_apellido_p;
    private javax.swing.JTextField txt_departamento_p;
    private javax.swing.JTextField txt_direccion_c;
    private javax.swing.JTextField txt_dni_cl;
    private javax.swing.JTextField txt_id_C;
    private javax.swing.JTextField txt_id_p;
    private javax.swing.JTextField txt_nombre_c;
    private javax.swing.JTextField txt_nombre_cl;
    private javax.swing.JTextField txt_nombre_p;
    private javax.swing.JTextField txt_tlf_c;
    private javax.swing.JTextField txt_tlf_cl;
    // End of variables declaration//GEN-END:variables
}
